queue_rules:
  - name: dependabot-nestjs-session
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (iamolegga)

pull_request_rules:
- name: merge pull requests from dependabot if CI passes
  conditions:
    - author~=^dependabot(|-preview)\[bot\]$
    - -check-failure~=build-lint-test
    - check-success~=build-lint-test
    - check-success=security/snyk (iamolegga)
  actions:
    queue:
      name: dependabot-nestjs-session
      method: rebase
